[build]
  command = "yarn build"
  publish = "build"

[[redirects]]
  from = "/cakes"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/aboutus"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

