[[redirects]]
  from = "/cakes"
  to = "/cakes"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
